import {
  MRT_ColumnDef,
  MaterialReactTable,
  useMaterialReactTable,
} from "material-react-table";
import { useMemo, useState } from "react";
import { IChampionshipStandings } from "src/@types/IChampionshipStandings";
import { IClassification } from "src/@types/IClassification";

const championshipStandings: IChampionshipStandings[] = [
  {
    NomeGrupo: "Grupo 1",
    Classificacao: [
      {
        Posicao: 1,
        Equipe: "Botafogo",
        Pontos: 79,
        Jogos: 38,
        Vitorias: 23,
        Empates: 10,
        Derrotas: 5,
        GolsPro: 59,
        GolsContra: 29,
        SaldoGols: 30,
        CartoesAmarelos: 7,
        CartoesVermelhos: 0,
        Aproveitamento: "69.3%",
        Movimentacao: null,
        MediaPontos: 79,
      },
      {
        Posicao: 2,
        Equipe: "Palmeiras",
        Pontos: 73,
        Jogos: 38,
        Vitorias: 22,
        Empates: 7,
        Derrotas: 9,
        GolsPro: 60,
        GolsContra: 33,
        SaldoGols: 27,
        CartoesAmarelos: 8,
        CartoesVermelhos: 0,
        Aproveitamento: "64.0%",
        Movimentacao: null,
        MediaPontos: 73,
      },
      {
        Posicao: 3,
        Equipe: "Flamengo",
        Pontos: 70,
        Jogos: 38,
        Vitorias: 20,
        Empates: 10,
        Derrotas: 8,
        GolsPro: 61,
        GolsContra: 42,
        SaldoGols: 19,
        CartoesAmarelos: 4,
        CartoesVermelhos: 0,
        Aproveitamento: "61.4%",
        Movimentacao: null,
        MediaPontos: 70,
      },
      {
        Posicao: 4,
        Equipe: "Fortaleza",
        Pontos: 68,
        Jogos: 38,
        Vitorias: 19,
        Empates: 11,
        Derrotas: 8,
        GolsPro: 53,
        GolsContra: 39,
        SaldoGols: 14,
        CartoesAmarelos: 10,
        CartoesVermelhos: 0,
        Aproveitamento: "59.6%",
        Movimentacao: "+1",
        MediaPontos: 68,
      },
      {
        Posicao: 5,
        Equipe: "Internacional",
        Pontos: 65,
        Jogos: 38,
        Vitorias: 18,
        Empates: 11,
        Derrotas: 9,
        GolsPro: 53,
        GolsContra: 36,
        SaldoGols: 17,
        CartoesAmarelos: 5,
        CartoesVermelhos: 0,
        Aproveitamento: "57.0%",
        Movimentacao: "-1",
        MediaPontos: 65,
      },
      {
        Posicao: 6,
        Equipe: "São Paulo",
        Pontos: 59,
        Jogos: 38,
        Vitorias: 17,
        Empates: 8,
        Derrotas: 13,
        GolsPro: 53,
        GolsContra: 43,
        SaldoGols: 10,
        CartoesAmarelos: 112,
        CartoesVermelhos: 9,
        Aproveitamento: "51,8%",
        Movimentacao: null,
        MediaPontos: 59,
      },
      {
        Posicao: 7,
        Equipe: "Corinthians",
        Pontos: 56,
        Jogos: 38,
        Vitorias: 15,
        Empates: 11,
        Derrotas: 12,
        GolsPro: 54,
        GolsContra: 45,
        SaldoGols: 9,
        CartoesAmarelos: 117,
        CartoesVermelhos: 10,
        Aproveitamento: "49,1%",
        Movimentacao: null,
        MediaPontos: 56,
      },
      {
        Posicao: 8,
        Equipe: "Bahia",
        Pontos: 53,
        Jogos: 38,
        Vitorias: 15,
        Empates: 8,
        Derrotas: 15,
        GolsPro: 49,
        GolsContra: 49,
        SaldoGols: 0,
        CartoesAmarelos: 85,
        CartoesVermelhos: 1,
        Aproveitamento: "46,5%",
        Movimentacao: null,
        MediaPontos: 53,
      },
      {
        Posicao: 9,
        Equipe: "Cruzeiro",
        Pontos: 52,
        Jogos: 38,
        Vitorias: 14,
        Empates: 10,
        Derrotas: 14,
        GolsPro: 43,
        GolsContra: 41,
        SaldoGols: 2,
        CartoesAmarelos: 101,
        CartoesVermelhos: 8,
        Aproveitamento: "45,6%",
        Movimentacao: null,
        MediaPontos: 52,
      },
      {
        Posicao: 10,
        Equipe: "Vasco",
        Pontos: 50,
        Jogos: 38,
        Vitorias: 14,
        Empates: 8,
        Derrotas: 16,
        GolsPro: 43,
        GolsContra: 56,
        SaldoGols: -13,
        CartoesAmarelos: 94,
        CartoesVermelhos: 7,
        Aproveitamento: "43,9%",
        Movimentacao: null,
        MediaPontos: 50,
      },
      {
        Posicao: 11,
        Equipe: "Vitória",
        Pontos: 47,
        Jogos: 38,
        Vitorias: 13,
        Empates: 8,
        Derrotas: 17,
        GolsPro: 45,
        GolsContra: 52,
        SaldoGols: -7,
        CartoesAmarelos: 112,
        CartoesVermelhos: 7,
        Aproveitamento: "41,2%",
        Movimentacao: null,
        MediaPontos: 47,
      },
      {
        Posicao: 12,
        Equipe: "Atlético-MG",
        Pontos: 47,
        Jogos: 38,
        Vitorias: 11,
        Empates: 14,
        Derrotas: 13,
        GolsPro: 47,
        GolsContra: 54,
        SaldoGols: -7,
        CartoesAmarelos: 107,
        CartoesVermelhos: 13,
        Aproveitamento: "41,2%",
        Movimentacao: null,
        MediaPontos: 47,
      },
      {
        Posicao: 13,
        Equipe: "Fluminense",
        Pontos: 46,
        Jogos: 38,
        Vitorias: 12,
        Empates: 10,
        Derrotas: 16,
        GolsPro: 33,
        GolsContra: 39,
        SaldoGols: -6,
        CartoesAmarelos: 119,
        CartoesVermelhos: 13,
        Aproveitamento: "40,4%",
        Movimentacao: null,
        MediaPontos: 46,
      },
      {
        Posicao: 14,
        Equipe: "Grêmio",
        Pontos: 45,
        Jogos: 38,
        Vitorias: 12,
        Empates: 9,
        Derrotas: 17,
        GolsPro: 44,
        GolsContra: 50,
        SaldoGols: -6,
        CartoesAmarelos: 93,
        CartoesVermelhos: 8,
        Aproveitamento: "39,5%",
        Movimentacao: null,
        MediaPontos: 45,
      },
      {
        Posicao: 15,
        Equipe: "Juventude",
        Pontos: 45,
        Jogos: 38,
        Vitorias: 11,
        Empates: 12,
        Derrotas: 15,
        GolsPro: 48,
        GolsContra: 59,
        SaldoGols: -11,
        CartoesAmarelos: 106,
        CartoesVermelhos: 13,
        Aproveitamento: "39,5%",
        Movimentacao: null,
        MediaPontos: 45,
      },
      {
        Posicao: 16,
        Equipe: "Bragantino",
        Pontos: 44,
        Jogos: 38,
        Vitorias: 10,
        Empates: 14,
        Derrotas: 14,
        GolsPro: 44,
        GolsContra: 48,
        SaldoGols: -4,
        CartoesAmarelos: 108,
        CartoesVermelhos: 5,
        Aproveitamento: "38,6%",
        Movimentacao: null,
        MediaPontos: 44,
      },
      {
        Posicao: 17,
        Equipe: "Athletico-PR",
        Pontos: 42,
        Jogos: 38,
        Vitorias: 11,
        Empates: 9,
        Derrotas: 18,
        GolsPro: 40,
        GolsContra: 46,
        SaldoGols: -6,
        CartoesAmarelos: 98,
        CartoesVermelhos: 10,
        Aproveitamento: "36,8%",
        Movimentacao: null,
        MediaPontos: 42,
      },
      {
        Posicao: 18,
        Equipe: "Criciúma",
        Pontos: 38,
        Jogos: 38,
        Vitorias: 9,
        Empates: 11,
        Derrotas: 18,
        GolsPro: 42,
        GolsContra: 61,
        SaldoGols: -19,
        CartoesAmarelos: 97,
        CartoesVermelhos: 6,
        Aproveitamento: "33,3%",
        Movimentacao: null,
        MediaPontos: 38,
      },
      {
        Posicao: 19,
        Equipe: "Atlético-GO",
        Pontos: 30,
        Jogos: 38,
        Vitorias: 7,
        Empates: 9,
        Derrotas: 22,
        GolsPro: 29,
        GolsContra: 58,
        SaldoGols: -29,
        CartoesAmarelos: 104,
        CartoesVermelhos: 12,
        Aproveitamento: "26,3%",
        Movimentacao: null,
        MediaPontos: 30,
      },
      {
        Posicao: 20,
        Equipe: "Cuiabá",
        Pontos: 30,
        Jogos: 38,
        Vitorias: 6,
        Empates: 12,
        Derrotas: 20,
        GolsPro: 29,
        GolsContra: 49,
        SaldoGols: -20,
        CartoesAmarelos: 119,
        CartoesVermelhos: 2,
        Aproveitamento: "26,3%",
        Movimentacao: null,
        MediaPontos: 30,
      },
    ],
  },
];

export function ChampionshipTable() {
  const [globalFilter, setGlobalFilter] = useState("");

  const columns = useMemo<MRT_ColumnDef<IClassification>[]>(
    () => [
      {
        accessorKey: "Posicao",
        header: "Posição",
        size: 10,
        muiTableBodyCellProps: {
          sx: { textAlign: "center" },
        },
        muiTableHeadCellProps: {
          sx: { textAlign: "center" },
        },
      },
      {
        accessorKey: "Equipe",
        header: "Equipe",
        size: 10,
        muiTableBodyCellProps: {
          sx: { textAlign: "center" },
        },
        muiTableHeadCellProps: {
          sx: { textAlign: "center" },
        },
      },
      {
        accessorKey: "Pontos",
        header: "Pontos",
        size: 10,
        muiTableBodyCellProps: {
          sx: { textAlign: "center" },
        },
        muiTableHeadCellProps: {
          sx: { textAlign: "center" },
        },
      },
      {
        accessorKey: "Jogos",
        header: "Jogos",
        size: 10,
        muiTableBodyCellProps: {
          sx: { textAlign: "center" },
        },
        muiTableHeadCellProps: {
          sx: { textAlign: "center" },
        },
      },
      {
        accessorKey: "Vitorias",
        header: "Vitórias",
        size: 10,
        muiTableBodyCellProps: {
          sx: { textAlign: "center" },
        },
        muiTableHeadCellProps: {
          sx: { textAlign: "center" },
        },
      },
      {
        accessorKey: "Empates",
        header: "Empates",
        size: 10,
        muiTableBodyCellProps: {
          sx: { textAlign: "center" },
        },
        muiTableHeadCellProps: {
          sx: { textAlign: "center" },
        },
      },
      {
        accessorKey: "Derrotas",
        header: "Derrotas",
        size: 10,
      },
      {
        accessorKey: "GolsPro",
        header: "Gols",
        size: 10,
        muiTableBodyCellProps: {
          sx: { textAlign: "center" },
        },
        muiTableHeadCellProps: {
          sx: { textAlign: "center" },
        },
      },
      {
        accessorKey: "GolsContra",
        header: "Gols contra",
        size: 10,
        muiTableBodyCellProps: {
          sx: { textAlign: "center" },
        },
        muiTableHeadCellProps: {
          sx: { textAlign: "center" },
        },
      },
      {
        accessorKey: "SaldoGols",
        header: "Saldo de gols",
        size: 10,
        muiTableBodyCellProps: {
          sx: { textAlign: "center" },
        },
        muiTableHeadCellProps: {
          sx: { textAlign: "center" },
        },
      },
      {
        accessorKey: "CartoesAmarelos",
        header: "Cartões amarelos",
        size: 10,
        muiTableBodyCellProps: {
          sx: { textAlign: "center" },
        },
        muiTableHeadCellProps: {
          sx: { textAlign: "center" },
        },
      },
      {
        accessorKey: "CartoesVermelhos",
        header: "Cartões vermelhos",
        size: 10,
        muiTableBodyCellProps: {
          sx: { textAlign: "center" },
        },
        muiTableHeadCellProps: {
          sx: { textAlign: "center" },
        },
      },
      {
        accessorKey: "Aproveitamento",
        header: "Aproveitamento",
        size: 10,
        muiTableBodyCellProps: {
          sx: { textAlign: "center" },
        },
        muiTableHeadCellProps: {
          sx: { textAlign: "center" },
        },
      },
      {
        accessorKey: "Movimentacao",
        header: "Movimentação",
        size: 10,
        muiTableBodyCellProps: {
          sx: { textAlign: "center" },
        },
        muiTableHeadCellProps: {
          sx: { textAlign: "center" },
        },
      },
      {
        accessorKey: "MediaPontos",
        header: "Media de pontos",
        size: 10,
        muiTableBodyCellProps: {
          sx: { textAlign: "center" },
        },
        muiTableHeadCellProps: {
          sx: { textAlign: "center" },
        },
      },
    ],
    []
  );

  const table = useMaterialReactTable({
    columns,
    data: championshipStandings[0].Classificacao,
    enableFullScreenToggle: false,
    enableDensityToggle: false,
    enableColumnFilters: false,
    enableHiding: false,
    enablePagination: false,
    enableColumnActions: false,
    onGlobalFilterChange: setGlobalFilter,
    state: {
      globalFilter,
      density: "compact",
    },
  });

  return <MaterialReactTable table={table} />;
}
